### ISSUE TITLE
run-plot.sh が落ちる 2022-06-23T12Z

### ISSUE THREAD

**Issue by etoyoda** [etoyoda/sfcmap#5]
ジョブ出力（メール）
```
/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse': 784: unexpected token at '{"@":"v7JJW","La":27.9,"Lo":127.9,"d":250,"f":9.3,"z":7640,"T":257.6,"Td":255.} (JSON::ParserError)
'
	from /usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /nwp/bin/distillobs.rb:7:in `block in <main>'
	from /nwp/bin/distillobs.rb:4:in `each_line'
	from /nwp/bin/distillobs.rb:4:in `each'
	from /nwp/bin/distillobs.rb:4:in `<main>'
```

**Comment by etoyoda** [comment]
落ちているのは bufrconv パッケージの distillobs.rb だが、コールサイン 7JJW なので TAC TEMP SHIP から作られているとわかる。実際 zloctac.txt にこの `255.}` がある。つまり sfcmap パッケージの問題。
```
$ grep -e '255\.}' zloctac.txt
2022-06-23T12:00Z/p400/v7JJW {"@":"v7JJW","La":27.9,"Lo":127.9,"d":250,"f":9.3,"z":7640,"T":257.6,"Td":255.}
```

**Comment by etoyoda** [comment]
丸め  detac-locate.rb:246 `to_json.gsub(/000000+\d\b/, '')`をやめると `"Td":255.00000000000003` だったようだ。なるほどそれはいかん。
